# Generated by Django 3.0.4 on 2020-07-01 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='count_year',
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End'),
        ),
        migrations.AddField(
            model_name='project',
            name='number_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='number_people_allocated',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='research',
            name='_email_data',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.CreateModel(
            name='PersonInEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_hours', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event', to='projects.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creation_date'],
                'permissions': [('can_upload_files', 'Can upload files'), ('can_delete_files', 'Can delete files'), ('can_view_files', 'Can view files')],
            },
        ),
    ]
