# Generated by Django 3.0.4 on 2020-07-03 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_auto_20200703_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaKeyEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('value', models.CharField(default='value not needed', max_length=200)),
                ('description', models.TextField(default='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meta_key_event', to='projects.Event')),
                ('meta_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meta_key_event', to='projects.MetaKey')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meta_key_event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event__id', '-creation_date'],
            },
        ),
    ]
