# Generated by Django 3.0.4 on 2020-07-04 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_metakeyevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinevent',
            name='delete_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delete_person_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personinevent',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='personinevent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_person_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
