# Generated by Django 3.0.4 on 2020-07-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200704_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinevent',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
