# Generated by Django 3.0.4 on 2020-07-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_metakeypersoninevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinevent',
            name='delete_date',
            field=models.DateTimeField(null=True, verbose_name='Delete Date'),
        ),
    ]
