# Generated by Django 3.0.4 on 2020-07-05 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_personinevent_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinevent',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='personinevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people_in_event', to='projects.Event'),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_people_allocated',
            field=models.IntegerField(default=0),
        ),
    ]
