# Generated by Django 3.0.4 on 2020-07-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200711_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakeyequipmentinevent',
            name='equipment_in_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meta_key_equipment_in_event', to='projects.EquipmentInEvent'),
        ),
    ]
