# Generated by Django 3.0.4 on 2020-07-11 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200711_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='equipmentinevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_in_event', to='projects.Event'),
        ),
    ]
